#!/usr/bin/env python

# Copyright 2024 Amazon.com and its affiliates; all rights reserved.
# This file is AWS Content and may not be duplicated or distributed without permission
import sys
from pathlib import Path
import datetime
import traceback
import yaml
import uuid
from textwrap import dedent
import os
import argparse
# sys.path.append(str(Path(__file__).parent.parent.parent.parent))
from src.utils.bedrock_agent import Agent, SupervisorAgent, Task, region, account_id

current_dir = os.path.dirname(os.path.abspath(__file__))
task_yaml_path = os.path.join(current_dir, "tasks.yaml")
agent_yaml_path = os.path.join(current_dir, "agents.yaml")

if __name__ == '__main__':
    export_report_tool = {
        "code": f"arn:aws:lambda:{region}:{account_id}:function:export_report",
        "definition": {
            "name": "export_report",
            "description": "Convert markdown-formatted report into a PDF file and Export it to S3",
            "parameters": {
                "markdown_report": {
                    "description": "markdown-formatted report generated by the agent",
                    "type": "string",
                    "required": True
                }
            }
        }
    }

    with open(agent_yaml_path, "r") as f:
        agent_yaml = yaml.safe_load(f)

    # Create two collaborator agents - content-writer-agent, formatted-report-writer-agent
    content_writer_agent = Agent(name='content-writer-agent', 
                                yaml_content=agent_yaml,
                                tools=None
                                )

    formatted_report_writer_agent = Agent(name='formatted-report-writer-agent', 
                                        yaml_content=agent_yaml, 
                                        tools=[export_report_tool]
                                        )
